apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: worlds.hello.k8s.io
spec:
  group: hello.k8s.io
  names:
    kind: World
    plural: worlds
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            name:
              type: string
            namespace:
              type: string
          required:
          - name
          - namespace
          type: object
        status:
          properties:
            message:
              type: string
            phase:
              type: string
          required:
          - phase
          - message
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
